name: file_encrypter_example
description: Demonstrates how to use the file_encrypter plugin.
publish_to: none
version: 2.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  file_encrypter:
    path: ../
  chewie: ^1.11.0
  dio: ^5.8.0+1
  path: ^1.9.1
  path_provider: ^2.1.5
  video_player: ^2.9.3


dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true